### ISSUE TITLE
Make `./quickstart` such that an error in the contract can be handled

### ISSUE THREAD

**Issue by friedger** [EOSIO/eosio-project-boilerplate-simple#17]
Currently, the setup is such that the scripts don't work if the contract on the first run has an error. After fixing the error in the contract, `quick_start.sh` fails (because the initialized file was not yet written but some parts of the init process already done.

It should be possible to run the scripts several times until the contract is fixed.

**Comment by rickykung** [comment]
Hi @friedger, the `quick_start.sh` gives you the fastest and most convenient way to start the project. It runs several scripts like `first_time_setup.sh` and scripts to start the eosio and react app. In `first_time_setup.sh`, we will force remove the pervious docker container and blockchain data folder to make sure the environment is clean. 

For your case, `first_time_setup.sh` should help. 
If not, i guess there are some modification to either the scripts or docker container name. Please try manually remove the previous docker container and `./eosio_docker/data` folder to verify.

**Comment by rickykung** [comment]
Please let us know if the problem persists.
