### ISSUE TITLE
Wallet-api-plugin is deprecated

### ISSUE THREAD

**Issue by MaxLarue** [EOSIO/eosio-project-boilerplate-simple#4]
There is no need anymore to use wallet_plugin and wallet_api_plugin when starting nodeos. As per the docs keosd now starts automatically with nodeos.
https://developers.eos.io/eosio-cpp/docs/introduction-to-smart-contracts

simply removing --plugin eosio::wallet_api_plugin --plugin eosio::wallet_plugin in init_blockchain.sh and continue_blockchain.sh should do it.

**Comment by rickykung** [comment]
Thank you for your suggestion @MaxLarue! We will update the source code.
